### PR TITLE
80 fix bugs

### LINKED ISSUE #80: Fix bugs
Fix swagger 

**PUT and POST and GET in /admin/rooms/ /rooms /reservations and /admin/reservations endpoint**:

- openingTime default value to proper format.
- closingTime default value to proper format.

Add **@PageableAsQueryParam** to all endpoints with pageable and set **@Schema(hidden = true)** to pageable objects.

Remove given endpoints from admin controllers

- GET /reservations
- GET /reservations/{id}
- GET /rooms/{id}
- GET /rooms
- GET /room-types/{id}
- GET /room-types

Remove unused imports

Fix bugs:
In *com.dsrm.dsrmbackend.mappers.RoleMapper#toRole* change id type from long to string
In *com.dsrm.dsrmbackend.mappers.RoomMapper#map* as above
In *com.dsrm.dsrmbackend.mappers.RoomMapper#toRoom* as above

Rename **openingTime** to **from** and **closingTime** to **to** in reservations dtos and entities.

Resources
https://springdoc.org/

### PR DESCRIPTION
**Pull request by Adrian-Rochminski**
closes: #80

### CODE REVIEW

File: src/main/java/com/dsrm/dsrmbackend/dto/ReservationDTO.java [hunk 1]
```diff
@@ -12,9 +12,9 @@
 @Setter
 public class ReservationDTO {
     private Room room;
-    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
+    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
     private LocalDateTime startTime;
```
Comment (Krizzuu) [inline src/main/java/com/dsrm/dsrmbackend/dto/ReservationDTO.java]: It should be "from" instead of "startTime", same with endTime

**Comment by Krizzuu** [comment]
I think you should add 
`@Schema(type="string", pattern = "HH:mm:ss")`
above LocalTime variables so it shows properly in swagger

**Review by Krizzuu — APPROVED** [review]
seems ok

**Review by HerbMat — APPROVED** [review]
