### PR TITLE
95 Fix room bug

### LINKED ISSUE #95: Fix create room
Add user to Room as keyOwner. 
Add to RoomTypeDTO id of type string.
In POST /admin/rooms in body add keyOwner attribute of string which is related user id. And attach user to room during room creation.

### PR DESCRIPTION
**Pull request by Adrian-Rochminski**
closes: #95

### CODE REVIEW

**Review by Krizzuu — CHANGES_REQUESTED** [review]
I think you there should be added keyOwner in RoomRequestDTO as task specified
"In POST /admin/rooms in body add keyOwner attribute of string which is related user id..."

**Review by Krizzuu — DISMISSED** [review]
looks ok

File: src/main/java/com/dsrm/dsrmbackend/mappers/RoomMapper.java [hunk 1]
```diff
@@ -7,7 +7,7 @@
 import org.mapstruct.Mapper;
 import org.mapstruct.Mapping;
 
-@Mapper(componentModel = "spring")
+@Mapper(componentModel = "spring", uses = UserMapper.class)
```
Comment (HerbMat) [inline src/main/java/com/dsrm/dsrmbackend/mappers/RoomMapper.java]: Do not use it that way. Please use getReferenceById to set a User in room like with roomType

**Review by HerbMat — CHANGES_REQUESTED** [review]

**Review by HerbMat — APPROVED** [review]
