### PR TITLE
46-fix-entity-ids

### LINKED ISSUE #46: Fix entity ids.
Change all entity ids from Long to String and remove @GeneratedValue annotation.

Now primary keys must have varchar type and all ids should be set using ```UUID.randomUUID().toString()```
in all post methods.

Please make change for all endpoints.

Example:
```
        User user = userMapper.toUser(userRequestDTO);
        user.setId(UUID.randomUUID().toString());
        return userRepo.save(user);
```

### PR DESCRIPTION
**Pull request by Krizzuu**
closes: #46

### CODE REVIEW

**Comment by HerbMat** [comment]
We need also change:

- com.dsrm.dsrmbackend.dto.UserRequestDTO#roles to List<String>
- com.dsrm.dsrmbackend.dto.ReservationRequestDTO#room to String
- com.dsrm.dsrmbackend.dto.ReservationRequestDTO#user  to String
- com.dsrm.dsrmbackend.dto.RoomRequestDTO#type to String

File: src/test/java/com/dsrm/dsrmbackend/ReservationControllerTests.java [hunk 1]
```diff
@@ -67,11 +69,19 @@ void addValidReservation() throws Exception {
...
         body.put("closingTime","2023-02-22 13:20:00");
         body.put("user",2);
-        this.mockMvc.perform(post("/reservations")
+        MvcResult result = this.mockMvc.perform(post("/reservations")
                         .contentType(MediaType.APPLICATION_JSON)
                         .content(objectMapper.writeValueAsString((body))))
                         .andExpect(status().isCreated())
-                        .andExpect(header().string("Location", "http://localhost/reservations/3"));
+                .andReturn();
+        String location = JsonPath.read(result.getResponse().getHeader("Location"), "$");
```
Comment (HerbMat) [inline src/test/java/com/dsrm/dsrmbackend/ReservationControllerTests.java]: We don't want to test GEt endpoint here. I would prefer if you would retrieve this data from repository. All changes in getter will break this test. It applies also to all tests below.

**Review by HerbMat — CHANGES_REQUESTED** [review]
Please fix.

**Review by HerbMat — APPROVED** [review]
