### PR TITLE
32 fix room tests

### LINKED ISSUE #32: Fix room tests.
In RoomTypeControllerTests and RoomControllerTests instead of testing directly controllers use MockMvc. 
It would also great to check all fields of response. and response status code.
Example https://www.baeldung.com/integration-testing-in-spring
Change controller method addRoom return type to void
Add Location header to responseChange ```@ClassRule``` annotation to ```@Container```
Remove annotation ```@RunWith``` in Tests
Change ```@Test ```annotations to``` org.junit.jupiter.api.Test```;
In RoomService before save add ```room.setRoomType(roomTyperepository.getReferenceById(room.getRoomType().getId()))```
Remove DsrmBackendApplicationTests
Add ```@Testcontainers``` annotation above test class
Add ```@Transactional``` to service method addRoom
Remove ```@RequiredArgsConstructor``` from test classes

Resources
https://reflectoring.io/spring-boot-web-controller-test/
https://shivaprasadgurram.hashnode.dev/how-to-add-location-header-to-spring-mvcs-post-response

### PR DESCRIPTION
**Pull request by Krizzuu**
closes #32

### CODE REVIEW

File: src/main/java/com/dsrm/dsrmbackend/controllers/RoomController.java [hunk 1]
```diff
@@ -25,10 +28,16 @@ public class RoomController {
...
     @PostMapping(value = "/rooms", consumes= MediaType.APPLICATION_JSON_VALUE)
-    public Room addRoom(@RequestBody RoomRequestDTO roomRequestDTO) {
-        return roomService.addRoom(roomRequestDTO);
+    public ResponseEntity<Room> addRoom(@RequestBody RoomRequestDTO roomRequestDTO) {
+        Room room = roomService.addRoom(roomRequestDTO);
+        URI location = ServletUriComponentsBuilder
+                .fromCurrentRequest()
+                .path("/{id}")
+                .buildAndExpand(room.getId()).toUri();
+        return ResponseEntity.created(location).body(room);
```
Comment (HerbMat) [inline src/main/java/com/dsrm/dsrmbackend/controllers/RoomController.java]: We don't want to return body, because we are returning Location header.

File: src/main/java/com/dsrm/dsrmbackend/controllers/RoomTypeController.java [hunk 2]
```diff
@@ -25,10 +28,16 @@ public class RoomTypeController {
     private final RoomTypeService roomTypeService;
     private final RoomTypeMapper roomTypeMapper;
 
+    @Transactional
     @ResponseStatus(HttpStatus.CREATED)
-    @PostMapping(value = "/room-types", consumes= MediaType.APPLICATION_JSON_VALUE)
-    public RoomType addRoomType(@RequestBody RoomTypeRequestDTO roomTypeRequestDTO) {
-        return roomTypeService.addRoomType(roomTypeRequestDTO);
+    @PostMapping(value = "/room-types", consumes = MediaType.APPLICATION_JSON_VALUE)
+    public ResponseEntity<RoomType> addRoomType(@RequestBody RoomTypeRequestDTO roomTypeRequestDTO) {
```
Comment (HerbMat) [inline src/main/java/com/dsrm/dsrmbackend/controllers/RoomTypeController.java]: As above

File: src/test/java/com/dsrm/dsrmbackend/RoomControllerTests.java [hunk 3]
```diff
@@ -1,92 +1,99 @@
...
+    private MockMvc mockMvc;
 
     @Test
-    public void insertValidRoom() {
-        RoomRequestDTO roomRequestDTO = new RoomRequestDTO("test", 203, 2, 3,
-                6, LocalTime.now(), LocalTime.now());
-        Room room = controller.addRoom(roomRequestDTO);
-        assertNotNull(room);
-        assertEquals(203, room.getRoomNumber());
+    public void insertValidRoom() throws Exception {
```
Comment (HerbMat) [inline src/test/java/com/dsrm/dsrmbackend/RoomControllerTests.java:37]: This test is failing

**Review by HerbMat — CHANGES_REQUESTED** [review]

File: src/main/java/com/dsrm/dsrmbackend/controllers/RoomController.java [hunk 4]
```diff
@@ -25,10 +28,16 @@ public class RoomController {
     private final RoomService roomService;
     private final RoomMapper roomMapper;
 
+    @Transactional
     @ResponseStatus(HttpStatus.CREATED)
     @PostMapping(value = "/rooms", consumes= MediaType.APPLICATION_JSON_VALUE)
-    public Room addRoom(@RequestBody RoomRequestDTO roomRequestDTO) {
-        return roomService.addRoom(roomRequestDTO);
+    public ResponseEntity<?> addRoom(@RequestBody RoomRequestDTO roomRequestDTO) {
```
Comment (HerbMat) [inline src/main/java/com/dsrm/dsrmbackend/controllers/RoomController.java]: why ```<?>``` ? It should ```ResponseEntity<Void>```

File: src/main/java/com/dsrm/dsrmbackend/controllers/RoomTypeController.java [hunk 5]
```diff
@@ -25,10 +28,16 @@ public class RoomTypeController {
     private final RoomTypeService roomTypeService;
     private final RoomTypeMapper roomTypeMapper;
 
+    @Transactional
     @ResponseStatus(HttpStatus.CREATED)
-    @PostMapping(value = "/room-types", consumes= MediaType.APPLICATION_JSON_VALUE)
-    public RoomType addRoomType(@RequestBody RoomTypeRequestDTO roomTypeRequestDTO) {
-        return roomTypeService.addRoomType(roomTypeRequestDTO);
+    @PostMapping(value = "/room-types", consumes = MediaType.APPLICATION_JSON_VALUE)
+    public ResponseEntity<?> addRoomType(@RequestBody RoomTypeRequestDTO roomTypeRequestDTO) {
```
Comment (HerbMat) [inline src/main/java/com/dsrm/dsrmbackend/controllers/RoomTypeController.java]: as above

**Review by HerbMat — CHANGES_REQUESTED** [review]

**Review by HerbMat — APPROVED** [review]
